# Generated by Django 2.2 on 2021-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_db_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mock',
            name='catch_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_mock',
            name='mock_response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
