# Generated by Django 2.2 on 2021-12-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20211211_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='mock_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='db_project',
            name='run_counts',
            field=models.IntegerField(default=0),
        ),
    ]
