# Generated by Django 2.2 on 2021-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_auto_20211212_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_mock',
            name='catch_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='db_mock',
            name='mock_response_body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
