# Generated by Django 2.2 on 2021-12-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20211212_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
