# Generated by Django 2.2 on 2021-12-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_db_project_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mock',
            name='model',
            field=models.CharField(blank=True, default='fx', max_length=30, null=True),
        ),
    ]
