# Generated by Django 2.2 on 2021-12-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_db_mock_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mock',
            name='response_headers',
            field=models.CharField(blank=True, default='{}', max_length=500, null=True),
        ),
    ]
