# Generated by Django 2.2 on 2021-12-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_db_mock_response_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mock',
            name='state_code',
            field=models.IntegerField(default=200),
        ),
    ]
