# Generated by Django 2.2 on 2021-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_db_mock_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mock',
            name='mock_response_body_lj',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
