# Generated by Django 2.2 on 2022-01-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_db_mock_mock_response_body_lj'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mock',
            name='mock_time',
            field=models.FloatField(default=0.0),
        ),
    ]
