# Generated by Django 2.2 on 2022-01-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_db_mock_mock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_mock',
            name='mock_time',
            field=models.FloatField(default=''),
        ),
    ]
