# Generated by Django 2.2 on 2022-01-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_auto_20220101_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_mock',
            name='mock_time',
            field=models.FloatField(default=0),
        ),
    ]
