# Generated by Django 2.2 on 2022-01-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_auto_20220101_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='catch_log',
            field=models.TextField(default='[]'),
        ),
    ]
