# Generated by Django 2.2 on 2022-01-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_db_project_catch'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='black_hosts',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project',
            name='white_hosts',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
