# Generated by Django 2.2 on 2022-01-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_auto_20220102_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='catch_time',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
